import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import Sidebar from "./components/layout/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="w-[95%] mx-auto my-3">
          <div className="lg:w-[208px] overflow-auto fixed top-[70px]">
            <Sidebar />
          </div>
          <div className="w-[90vw]">{children}</div>
        </div>
      </body>
    </html>
  );
}
