import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import Sidebar from "./components/layout/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="w-[95%] mx-auto my-3 flex items-center gap-5">
          <div className="lg:w-[208px] sm:w-[180px] hidden sm:block  w-[10vw] overflow-auto fixed top-[70px] border border-yellow-400">
            <Sidebar />
          </div>
          <div className="fixed sm:left-[220px] lg:left-[250px] xl:left-[265px] xs:left-0 xs:w-[100%] sm:w-[85%] w-[100%]  border border-gray-200 top-[70px]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
